name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./build

      # 安裝 LINE Notify 套件
      - name: Install LINE Notify
        run: npm install @line/bot-sdk

      # 發送 LINE Notify 通知
      - name: Send LINE Notify
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }} # 使用之前設定的 Secrets
        run: |
          echo "Sending LINE Notify..."
          const axios = require("axios");
          const token = process.env.LINE_NOTIFY_TOKEN;
          const message = 'Deployment to GitHub Pages is successful!';

          axios.post('https://notify-api.line.me/api/notify', `message=${message}`, {
            headers: {
              'Content-Type': 'application/x-www-form-urlencoded',
              'Authorization': `Bearer ${token}`,
            },
          })
          .then(response => {
            console.log('Docusaurus又更厲害拉');
          })
          .catch(error => {
            console.error('Docusaurus因為 ' + error.message + ' 跌了一跤');
            throw error;
          })